# Generated by Django 4.2.4 on 2023-08-25 20:17

from django.db import migrations, models
from django.contrib.auth.models import User


def create_superuser(apps, schema_editor):
    User.objects.create_superuser(username='admin', password='admin', email='admin@example.com')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publicationDate', models.DateField(null=True)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(create_superuser),

    ]
