# Generated by Django 4.0.3 on 2023-08-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='delete_flag',
        ),
    ]
