# Generated by Django 4.0.3 on 2023-08-26 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_date_created_category_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publicationDate',
            new_name='publication_date',
        ),
    ]
