# Generated by Django 4.0.3 on 2023-08-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rename_category_book_category_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
